[project]
name = "purge"
version = "0.1.0"
description = "Minimalistic Discord message deletion bot"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask-discord-interactions>=2.1.2",
    "gunicorn>=26.2.0",
    "python-i18n[yaml]>=0.3.9",
    "ruff>=0.15.21",
    "ty>=0.0.59",
]
